### ISSUE TITLE
Cannot play video on iOS

### ISSUE THREAD

**Issue by mtrfnvwork** [fluttercommunity/chewie#609] opened 2022-02-25 02:54 UTC
Hello!

When I try to play a video on iOS using the link https://data-big.ru/v1/file/y6845e4k4pb49ccsgdu3kmc6ydeuyqxo9zedszkohnkoqkwuq3, I get an error

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Operation stopped, null, null)`

When playing on Android, this error does not occur

My code:

```
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _initialized = false;
  late ChewieController _controller;

  @override
  void initState() {
    var videoPlayerController =
        VideoPlayerController.network('https://data-big.ru/v1/file/y6845e4k4pb49ccsgdu3kmc6ydeuyqxo9zedszkohnkoqkwuq3');

    videoPlayerController.initialize().then((value) {
      _controller = ChewieController(
        videoPlayerController: videoPlayerController,
        autoPlay: true,
      );

      setState(() {
        _initialized = true;
      });
    });

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: _initialized
              ? Chewie(
                  controller: _controller,
                )
              : const CircularProgressIndicator(),
        ),
      ),
    );
  }
}
```

**Comment by diegotori** [comment] 2022-02-25 16:27
@mtrfnvwork couple of things: 1) Please create a separate project with this reproducible sample, and 2) the video link you just posted does not open for me, due to SSL related issues.

Please repost the video link to another provider, so that I can further diagnose this issue. Thanks.

**Comment by mtrfnvwork** [comment] 2022-02-25 16:50
@diegotori 1) A ran this code in new flutter project, 2) Can you download the video in browser? SSL is valid. I tried open link in Postman and now I see that certificate is valid: "Valid Until Jan 30 01:46:36 2023 GMT"

**Comment by maherjaafar** [comment] 2022-02-25 19:03
@mtrfnvwork I am trying to run your code...

**Comment by maherjaafar** [comment] 2022-02-25 19:38
@mtrfnvwork 
I tried to use your link only with the [video_player's](https://pub.dev/packages/video_player#ios) example. It throws the same exception.

My code ⬇️
```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://data-big.ru/v1/file/y6845e4k4pb49ccsgdu3kmc6ydeuyqxo9zedszkohnkoqkwuq3')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

**Comment by maherjaafar** [comment] 2022-02-25 19:38
@diegotori this issue should be related to [video_player](https://pub.dev/packages/video_player), shall we close it?

**Comment by mtrfnvwork** [comment] 2022-02-25 19:41
@maherjaafar Could you run my code? I tried to create new flutter_project, install chewie and paste the code above. Project build correctly

**Comment by maherjaafar** [comment] 2022-02-25 20:25
The project builds correctly but the problem happens but from your video.

**Comment by mtrfnvwork** [comment] 2022-02-25 20:26
What's the problem with video? On Android the application works well

**Comment by diegotori** [comment] 2022-02-25 20:27
@maherjaafar if this is 100% due to `video_player` then it's something out of Chewie's control. I would close it.

@mtrfnvwork please post your issue on the [Flutter Project Issue Board](https://github.com/flutter/flutter/issues/), since Chewie is merely UI that controls the `video_player` library, maintained by the Flutter Team.

**Closed** 2022-02-25 20:32 UTC
Labels: video_player
